#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xkbcomp
Version  : 1.3.1
Release  : 6
URL      : http://xorg.freedesktop.org/releases/individual/app/xkbcomp-1.3.1.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/app/xkbcomp-1.3.1.tar.gz
Summary  : XKB keymap compiler
Group    : Development/Tools
License  : HPND
Requires: xkbcomp-bin
Requires: xkbcomp-doc
BuildRequires : bison
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbfile)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
X Keyboard Extension
--------------------
The X Keyboard Extension essentially replaces the core protocol definition of
keyboard. The extension makes possible to clearly and explicitly specify most
aspects of keyboard behaviour on per-key basis and to more closely track the
logical and physical state of the keyboard. It also includes a number of
keyboard controls designed to make keyboards more accessible to people with
physical impairments.

%package bin
Summary: bin components for the xkbcomp package.
Group: Binaries

%description bin
bin components for the xkbcomp package.


%package dev
Summary: dev components for the xkbcomp package.
Group: Development
Requires: xkbcomp-bin
Provides: xkbcomp-devel

%description dev
dev components for the xkbcomp package.


%package doc
Summary: doc components for the xkbcomp package.
Group: Documentation

%description doc
doc components for the xkbcomp package.


%prep
%setup -q -n xkbcomp-1.3.1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xkbcomp

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
